test with automatic upload

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -1,32 +1,20 @@
-name: Lighthouse
-
-on:
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
-
+name: Build and Run Lighthouse CI
+on: [push]
 jobs:
-  lighthouse:
+  lhci:
+    name: Lighthouse CI
     runs-on: ubuntu-latest
-
     steps:
-    - uses: actions/checkout@v2
-
-    - name: Install Node Modules
-      run: yarn
-
-    - name: Build
-      run: |
-        yarn build
-
-    - name: Lighthouse
-      run: |
-        yarn test:lh:ci --url=http://localhost:9000/using-wpp-targets-file-together-sitecore/
-        yarn test:lh:assert
-  
-    - name: Archive Lighthouse results
-      uses: actions/upload-artifact@v1
-      with:
-        name: lighthouse-report
-        path: .lighthouseci
+      - uses: actions/checkout@v2
+      - name: Use Node.js 10.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: 10.x
+      - name: yarn, build
+        run: |
+          yarn
+          yarn build
+      - name: run Lighthouse CI
+        run: |
+          yarn add -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
